### ISSUE TITLE
0.2.1 pipx is broken

### ISSUE THREAD

**Issue by svandragt** [svandragt/fafi#93]
```
root@unanimous-staghound:~/.local/bin# ./fafi 
Traceback (most recent call last):
  File "./fafi", line 5, in <module>
    from fafi.fafi import cli
  File "/root/.local/pipx/venvs/fafi/lib/python3.8/site-packages/fafi/fafi.py", line 7, in <module>
    import appdata
ModuleNotFoundError: No module named 'appdata'
```

**Comment by svandragt** [comment]
Fixed by a01a350aeb2c6a451a33c188658334e809eda86c
